apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: default
  labels: { app: dummysite-controller }
spec:
  replicas: 1
  selector:
    matchLabels: { app: dummysite-controller }
  template:
    metadata:
      labels: { app: dummysite-controller }
    spec:
      serviceAccountName: dummysite-controller
      containers:
        - name: controller
          image: ghcr.io/maxim955827848/dummysite-controller:1.0
