# Exercise 1.2 "Declarative approach"
# Replace <DOCKERHUB_USER> with your Docker Hub username after you build & push,
# OR import the locally-built image into k3d (see repo README).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: <DOCKERHUB_USER>/log-output:1.0
