apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: project-storage
          persistentVolumeClaim:
            claimName: project-pvc
      containers:
        - name: project
          image: ghcr.io/maxim955827848/the-project:1.0
          env:
            - name: PORT
              value: "3000"
            - name: DATA_DIR
              value: /usr/src/app/data
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: project-storage
              mountPath: /usr/src/app/data
