apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: ghcr.io/maxim955827848/log-output-writer:2.0
          resources:        # ex 3.08 / 3.09
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          env:
            - name: SHARED_DIR
              value: /usr/src/app/files
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: ghcr.io/maxim955827848/log-output-reader:2.0
          ports:
            - containerPort: 3000
          resources:        # ex 3.08 / 3.09
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: PORT
              value: "3000"
            - name: SHARED_DIR
              value: /usr/src/app/files
            - name: PINGPONG_URL
              value: http://ping-pong-svc:2346/pings
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
